### ISSUE TITLE
`as_global` does not work with complex types

### ISSUE THREAD

**Issue by JimOverholt** [cisco-open/cisco-catalyst-wan-sdk#57]
### Summary

`as_global` does not work with `List[str]`

### Reproduction script

```python
aaa = AAA(
    parcel_name="test",
    parcel_description="test2",
    server_auth_order=as_global(["local"]),
)
```

Workaround:
```python
aaa = AAA(
    parcel_name="test",
    parcel_description="test2",
    server_auth_order=Global[List[str]](value=['local']),
)
```

### On what platform(s) does it occur?

Not Applicable

### Issue Severity

Medium: There is a workaround

**Comment by JimOverholt** [comment]
This issue was migrated from an old repository: https://github.com/CiscoDevNet/catalystwan/issues/477

**Comment by jpkrajewski** [comment]
Fixed in https://github.com/cisco-open/cisco-catalyst-wan-sdk/pull/625
