### ISSUE TITLE
[UX2.0] Add models for "transport vpn" and "transport vpn interface ethernet"

### ISSUE THREAD

**Issue by tzarski0** [cisco-open/cisco-catalyst-wan-sdk#621]
### Description

Path: cisco-catalyst-wan-sdk/catalystwan/models/configuration/feature_profile/sdwan/transport/

Add models for "transport vpn" and "transport vpn interface ethernet"

**Comment by jpkrajewski** [comment]
We have added transport vpn and transport vpn interface ethernet. They are on dev-uxmt branch, we will be merging this to main soon.
- catalystwan/models/configuration/feature_profile/sdwan/transport/vpn.py::TransportVpnParcel
- catalystwan/models/configuration/feature_profile/sdwan/transport/wan/interface/ethernet.py::InterfaceEthernetParcel
