### ISSUE TITLE
[UX2.0] Add models for "service vpn" and "service vpn interface ethernet"

### ISSUE THREAD

**Issue by tzarski0** [cisco-open/cisco-catalyst-wan-sdk#622]
### Description

Path: cisco-catalyst-wan-sdk/catalystwan/models/configuration/feature_profile/sdwan/service/

Add models for "service vpn" and "service vpn interface ethernet"

**Comment by jpkrajewski** [comment]
We have added this model and endpoints. It is on dev-uxmt branch, we will be merging this to main soon.
- models: `catalystwan/models/configuration/feature_profile/sdwan/service/lan/vpn.py`
- endpoints: `catalystwan/api/feature_profile_api.py::ServiceFeatureProfileAPI`
