### ISSUE TITLE
Add devices to DeviceModel class

### ISSUE THREAD

**Issue by JimOverholt** [cisco-open/cisco-catalyst-wan-sdk#65]
### Description

Please add following devices to mentioned class:
vedge-C1111-4PLTEEA
vedge-C1161X-8PLTEP
vedge-C8300-2N2S-4T2X
vedge-C8500L-8S4X
vedge-C8200-1N-4T
vedge-C8200L-1N-4T

**Comment by JimOverholt** [comment]
This issue was migrated from an old repository: https://github.com/CiscoDevNet/catalystwan/issues/375

**Comment by cicharka** [comment]
Closing this one as all devices are already present in https://github.com/cisco-open/cisco-catalyst-wan-sdk/blob/main/catalystwan/utils/device_model.py
